# Generated by Django 4.1.4 on 2022-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_snipcartsettings_productcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomfield',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
