# Generated by Django 4.1.4 on 2022-12-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
