# Generated by Django 4.1.4 on 2022-12-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('30', '30'), ('36', '36'), ('40', '40')], default='30', max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
