# Generated by Django 4.1.4 on 2022-12-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_mymodel_remove_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='color',
            new_name='size',
        ),
    ]
