# Generated by Django 4.1.4 on 2022-12-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_color_mymodel_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
