# Generated by Django 4.1.4 on 2022-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('30', '30'), ('36', '36'), ('40', '40')], max_length=50, null=True),
        ),
    ]
