# Generated by Django 4.1.4 on 2022-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustomfield',
            name='options',
            field=models.CharField(blank=True, choices=[('30', '30'), ('36', '36'), ('40', '40')], max_length=500, null=True),
        ),
    ]
