# Generated by Django 4.1.4 on 2022-12-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_productcustomfield_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustomfield',
            name='size',
            field=models.CharField(choices=[('30', '30'), ('36', '36'), ('40', '40')], max_length=10, null=True),
        ),
    ]
