# Generated by Django 4.1.4 on 2022-12-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_productcustomfield_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('O', 'Offen'), ('T', 'Vergeben'), ('W', 'In Arbeit'), ('C', 'Komplett'), ('A', 'Abgebrochen')], default='O', max_length=1),
        ),
    ]
