# Generated by Django 4.1.4 on 2022-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
    ]
